### ISSUE TITLE
Not compat w ssh config file

### ISSUE THREAD

**Issue by ndreckshage** [vishwanatharondekar/gitlab-cli#36]
```
URL of remote obtained: my_ssh_config_alias:project/repo.git
gitlab host obtained: git.company.com

Remote at which branch_x is tracked is not a gitlab repository at git.company.com
```

**Comment by vishwanatharondekar** [comment]
Thanks for reporting. I had added this check very early in the project development and was not sure if this will cause a problem somewhere. I will remove this check since it doesnt make sense. GITLAB_HOST is enough to create merge request. 

Although, I realised that this would have been broken anyway in parsing the project info from remote url. I am fixing that in https://github.com/vishwanatharondekar/gitlab-cli/pull/35 by updating the regular expression. 

Will create separate pull request for removing this check.

**Comment by vishwanatharondekar** [comment]
@ndreckshage have merged the fix in master. You can reinstall and try again. Let me know if you face any issues.

Closing this.
